let
    Source = Csv.Document(File.Contents("D:\Study\Practice Space\powerbi-version-control\data\US Population Estimates.csv"),[Delimiter=",", Columns=106, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sex", type text}, {"Origin", type text}, {"Race", type text}, {"Year", Int64.Type}, {"Total Population", Int64.Type}, {"Age 0", Int64.Type}, {"Age 1", Int64.Type}, {"Age 2", Int64.Type}, {"Age 3", Int64.Type}, {"Age 4", Int64.Type}, {"Age 5", Int64.Type}, {"Age 6", Int64.Type}, {"Age 7", Int64.Type}, {"Age 8", Int64.Type}, {"Age 9", Int64.Type}, {"Age 10", Int64.Type}, {"Age 11", Int64.Type}, {"Age 12", Int64.Type}, {"Age 13", Int64.Type}, {"Age 14", Int64.Type}, {"Age 15", Int64.Type}, {"Age 16", Int64.Type}, {"Age 17", Int64.Type}, {"Age 18", Int64.Type}, {"Age 19", Int64.Type}, {"Age 20", Int64.Type}, {"Age 21", Int64.Type}, {"Age 22", Int64.Type}, {"Age 23", Int64.Type}, {"Age 24", Int64.Type}, {"Age 25", Int64.Type}, {"Age 26", Int64.Type}, {"Age 27", Int64.Type}, {"Age 28", Int64.Type}, {"Age 29", Int64.Type}, {"Age 30", Int64.Type}, {"Age 31", Int64.Type}, {"Age 32", Int64.Type}, {"Age 33", Int64.Type}, {"Age 34", Int64.Type}, {"Age 35", Int64.Type}, {"Age 36", Int64.Type}, {"Age 37", Int64.Type}, {"Age 38", Int64.Type}, {"Age 39", Int64.Type}, {"Age 40", Int64.Type}, {"Age 41", Int64.Type}, {"Age 42", Int64.Type}, {"Age 43", Int64.Type}, {"Age 44", Int64.Type}, {"Age 45", Int64.Type}, {"Age 46", Int64.Type}, {"Age 47", Int64.Type}, {"Age 48", Int64.Type}, {"Age 49", Int64.Type}, {"Age 50", Int64.Type}, {"Age 51", Int64.Type}, {"Age 52", Int64.Type}, {"Age 53", Int64.Type}, {"Age 54", Int64.Type}, {"Age 55", Int64.Type}, {"Age 56", Int64.Type}, {"Age 57", Int64.Type}, {"Age 58", Int64.Type}, {"Age 59", Int64.Type}, {"Age 60", Int64.Type}, {"Age 61", Int64.Type}, {"Age 62", Int64.Type}, {"Age 63", Int64.Type}, {"Age 64", Int64.Type}, {"Age 65", Int64.Type}, {"Age 66", Int64.Type}, {"Age 67", Int64.Type}, {"Age 68", Int64.Type}, {"Age 69", Int64.Type}, {"Age 70", Int64.Type}, {"Age 71", Int64.Type}, {"Age 72", Int64.Type}, {"Age 73", Int64.Type}, {"Age 74", Int64.Type}, {"Age 75", Int64.Type}, {"Age 76", Int64.Type}, {"Age 77", Int64.Type}, {"Age 78", Int64.Type}, {"Age 79", Int64.Type}, {"Age 80", Int64.Type}, {"Age 81", Int64.Type}, {"Age 82", Int64.Type}, {"Age 83", Int64.Type}, {"Age 84", Int64.Type}, {"Age 85", Int64.Type}, {"Age 86", Int64.Type}, {"Age 87", Int64.Type}, {"Age 88", Int64.Type}, {"Age 89", Int64.Type}, {"Age 90", Int64.Type}, {"Age 91", Int64.Type}, {"Age 92", Int64.Type}, {"Age 93", Int64.Type}, {"Age 94", Int64.Type}, {"Age 95", Int64.Type}, {"Age 96", Int64.Type}, {"Age 97", Int64.Type}, {"Age 98", Int64.Type}, {"Age 99", Int64.Type}, {"Age 100", Int64.Type}}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"Sex", "Origin", "Race", "Year", "Total Population"}, "Attribute", "Value"),
    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Age"}, {"Value", "Population"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Total Population"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","Age ","",Replacer.ReplaceText,{"Age"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Age", Int64.Type}})
in
    #"Changed Type1"